package main

import (
	"encoding/json"
	"net/http"
	"os"
	"runtime/pprof"
	"time"
)

type AutoGenerated struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Actor struct {
		ID         int    `json:"id"`
		Login      string `json:"login"`
		GravatarID string `json:"gravatar_id"`
		URL        string `json:"url"`
		AvatarURL  string `json:"avatar_url"`
	} `json:"actor"`
	Repo struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"repo"`
	Payload struct {
		Ref          string `json:"ref"`
		RefType      string `json:"ref_type"`
		MasterBranch string `json:"master_branch"`
		Description  string `json:"description"`
		PusherType   string `json:"pusher_type"`
	} `json:"payload"`
	Public    bool      `json:"public"`
	CreatedAt time.Time `json:"created_at"`
}

func main() {
	res, err := http.DefaultClient.Get("http://localhost:8000")
	if err != nil {
		panic(err.Error())
	}
	defer res.Body.Close()

	var models []AutoGenerated
	if err := json.NewDecoder(res.Body).Decode(&models); err != nil {
		panic(err.Error())
	}

	if len(models) == 0 {
		panic("models must not be empty")
	}

	f, _ := os.Create("mem.pprof")
	pprof.WriteHeapProfile(f)
	f.Close()
}
